[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sebastian Hernandez", email = "tiancho99@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.42.96",
    "fastapi[standard]>=0.136.1",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "uvicorn[standard]>=0.46.0",
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]

[tool.fastapi]
entrypoint = "app.main:app"
